In [3]:
import numpy as np
import pandas as pd

In [2]:
import torch

scalar_tensor = torch.tensor(42)
scalar_tensor

tensor(42)

In [3]:
list_tensor = torch.tensor([1,2,3])
print(list_tensor)

tensor([1, 2, 3])


In [5]:
matrix_tensor = torch.tensor([[1,2,4], [2,3,4],[3,4,5]])
matrix_tensor

tensor([[1, 2, 4],
        [2, 3, 4],
        [3, 4, 5]])

In [9]:
n_dim_matrx_tensor = torch.tensor([[[1], [2]], [[3], [4]]])
n_dim_matrx_tensor

tensor([[[1],
         [2]],

        [[3],
         [4]]])

In [11]:
tensor = torch.tensor("Hello world!")
print(tensor)

TypeError: new(): invalid data type 'str'

In [12]:
np_array = np.array([1, 2, 3])
tensor = torch.tensor(np_array)
tensor

tensor([1, 2, 3])

In [16]:
df = pd.DataFrame({"numbers": [1, 2, 3]})
df

,numbers
0,1
1,2
2,3


In [17]:
df_tensor = torch.tensor(df.numbers)
df_tensor

tensor([1, 2, 3])

In [29]:
random_tensor = torch.rand(2, 2)
random_tensor

tensor([[0.4533, 0.8190],
        [0.7361, 0.7632]])

In [28]:
zeros_tensor = torch.zeros(2,2)
zeros_tensor

tensor([[0., 0.],
        [0., 0.]])

In [31]:
ones_tensor = torch.ones(2,2)
ones_tensor

tensor([[1., 1.],
        [1., 1.]])

In [32]:
fill_tensor = torch.full((2,2), fill_value=2)
fill_tensor

tensor([[2, 2],
        [2, 2]])

In [34]:
range_tensor = torch.arange(3)
range_tensor

tensor([0, 1, 2])

In [35]:
tensor.dtype

torch.int64

In [37]:
tensor = torch.FloatTensor([1, 2, 3])
tensor

tensor([1., 2., 3.])

In [4]:
tensor = torch.tensor([1, 2, 3], device="cuda")
tensor.device

device(type='cuda', index=0)

In [9]:
tensor = torch.tensor([1,2,3], dtype=torch.int32)
tensor.device


device(type='cpu')

In [10]:
tensor.to("cuda").device

device(type='cuda', index=0)

In [13]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = x - y
z

tensor([0.3333, 0.5000])

In [14]:
tensor = torch.tensor([1, 2, 3])
mask = tensor > 1
mask

tensor([False,  True,  True])

In [15]:
tensor[mask]

tensor([2, 3])

In [19]:
x = torch.tensor([[1, 2], [3, 4]])
y = torch.tensor([[3, 4], [1, 2]])
z = x + y
z

tensor([[4, 6],
        [4, 6]])

In [23]:
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
z = torch.dot(x,y)
z

tensor(11)

In [27]:
tensor = torch.tensor([1,2,3])
tensor.sum()


tensor(6)

In [28]:
tensor.max()

tensor(3)

In [42]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor.min()

tensor(1)

In [41]:
import torch

tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])

# Access the .values attribute of the namedtuple
min_values = tensor.min(dim=-1).values

print(min_values)


tensor([1, 4])


In [52]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor.argmax(dim=-1)

tensor([2, 2])

In [54]:
tensor = torch.tensor([[1, 2, 3]])
tensor.argmax()

tensor(2)

In [55]:
tensor = torch.tensor([[1, 2, 3]])
tensor.argmax(dim=-1)

tensor([2])

In [59]:
x = torch.tensor([[1, 2, 3]])
y = torch.tensor([[4, 5, 6]])
z = torch.tensor([[1, 2, 3]])
c = torch.tensor([[1, 2, 4]])

print(x.equal(y))
print(x.equal(z))
print(x.equal(c))

False
True
False


In [61]:
tensor = torch.tensor([1, 5, 16])
print(tensor.clip(min=2, max=8))  #clip function used to change min and maxx

tensor([2, 5, 8])


In [66]:
tensor = torch.tensor([1, 2, 3, 4, 5])
result = torch.where(tensor>2, tensor,-1)
print(result)

tensor([-1, -1,  3,  4,  5])


In [67]:
tensor[:2]

tensor([1, 2])

In [68]:
tensor[2:]

tensor([3, 4, 5])

In [70]:
tensor[1:3]

tensor([2, 3])

In [71]:
indeices = [0, 4]
tensor[indeices]

tensor([1, 5])

In [73]:
tensor.shape

torch.Size([5])

In [76]:
tensor = torch.tensor([1, 2, 3, 4, 5, 6])
matrix = tensor.reshape(2,3)
print(matrix)
matrix.shape

tensor([[1, 2, 3],
        [4, 5, 6]])


torch.Size([2, 3])

In [77]:
matrix.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [80]:
matrix.permute(1,0)

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [83]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
result = torch.cat([x, y])

In [84]:
result

tensor([1, 2, 3, 4, 5, 6])

In [85]:
result = torch.stack([x, y])

In [86]:
result

tensor([[1, 2, 3],
        [4, 5, 6]])

In [87]:
tensor = torch.tensor([1, 2, 3])
torch.save(tensor, "my_tensor.t")

In [88]:
loaded_tensor = torch.load("my_tensor.t")
loaded_tensor

tensor([1, 2, 3])

## Autograd

In [108]:
x = torch.randn(3)
print(x)

tensor([ 0.1517, -0.9524, -1.1404])


In [109]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([-0.8238, -0.3905, -0.3851], requires_grad=True)


In [119]:
y = x+2
print(y)

z = y*y*2
print(z)
z = z.mean()
print(z)

tensor([1.1762, 1.6095, 1.6149], grad_fn=<AddBackward0>)
tensor([2.7669, 5.1807, 5.2157], grad_fn=<MulBackward0>)
tensor(4.3878, grad_fn=<MeanBackward0>)


In [120]:
z.backward() #dz/dx

In [117]:
print(x.grad)

tensor([1.5683, 2.1459, 2.1532])
